stripe-samples/issuing-treasury

- components/Stripe/CardDetailsWidget.js
Removed the retrieveIssuingCard references from the cardDetails widget.
> Removed retrieveIssuingCard references

- components/Stripe/FaTransactionsExtendedWidget.js
- components/Stripe/FaTransactionsWidget.js
- pages/dashboard.js
- pages/financial_account.js
- utils/stripe_helpers.js
Added an expanded FA transactions helper that allows to display the regulatory receipts on certain FA transactions.
> Updates on the FA transactions widget

- components/Stripe/CardholderCreateWidget.js
- components/Stripe/CardholderUpdateWidget.js
- components/Stripe/CardholderWidget.js
- pages/api/update_cardholder.js
Updated the Cardholder related widgets to include the tracking and acceptance of the cardholder terms of service.
> Added a flow for cardholder TOS acceptance

- .env.example
- src/pages/auth/register.tsx
- src/utils/demo-helpers.ts
* Fixes the demo mode environment variable that wasn't being loaded on the clientside
> Fix demo mode environment variable

- db/setup-database.postgres.sh
- prisma/schema.prisma
- render.yaml
- src/layouts/dashboard/account-popover.tsx
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/cards/card-key.ts
- src/pages/api/register.ts
- src/pages/auth/login.tsx
- src/pages/auth/register.tsx
- src/types/next-auth.d.ts
- src/utils/authentication.ts
- src/utils/demo-helpers.ts
* Switches to autogenerated emails
* Removes username as an input
> Switch to autogenerated emails

- src/pages/api/onboard.ts
- src/pages/onboard.tsx
- src/utils/onboarding-helpers.ts
* Allows skipping onboarding and going straight to the demo
> Allow skipping onboarding

- src/layouts/dashboard/side-nav.tsx
- src/utils/onboarding-helpers.ts
* Fixes a bug I introduced in the onboarding helper return type
> Fix function return type

- src/pages/api/onboard.ts
> Remove console.log

- src/pages/api/onboard.ts
- src/pages/onboard.tsx
* Changes the way we handle the response from the onboarding endpoint when skipping onboarding
> Tweak redirect when skipping onboarding

- src/layouts/auth/layout.tsx
- src/layouts/dashboard/account-popover.tsx
- src/layouts/dashboard/side-nav.tsx
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/cards/[cardId]/switch-card-status.ts
- src/pages/api/onboard.ts
- src/pages/api/register.ts
- src/pages/auth/register.tsx
- src/pages/cards/[cardId].tsx
- src/pages/onboard.tsx
- src/sections/cardholders/cardholder-create-widget.tsx
- src/sections/cardholders/cardholder-update-widget.tsx
- src/sections/financial-account/send-money-wizard-dialog.tsx
- src/sections/overview/transaction-flow-details.tsx
- src/sections/test-data/test-data-create-payment-link.tsx
- src/sections/test-data/test-data-create-payout.tsx
- src/utils/authentication.ts
- src/utils/demo-helpers.ts
* Moves the business name gathering to the onboarding page
> Revamp the login/registration/onboarding flow (Part 2)

- src/pages/api/onboard.ts
* Fixes the business name not being set when choosing to not skip onboarding in demo mode
> Revamp the login/registration/onboarding flow (Part 3)

- src/pages/onboard.tsx
> Remove unused variables

- src/layouts/auth/layout.tsx
* Adds a cookie banner that can be dismissed and won't show up again for the user
> Add a cookie banner

- src/layouts/auth/layout.tsx
* Fixes z-index ordering of cookie banner
> Fix z-index ordering of cookie banner

- src/layouts/dashboard/config.tsx
- src/layouts/dashboard/side-nav.tsx
- src/pages/index.tsx
- src/pages/test-data.tsx
* Removes unused variables and imports
> Remove unused variables and imports

- src/sections/cardholders/cardholders-table.tsx
* Fixes CSS issue with select component
> Fix CSS issue with select component

- .github/dependabot.yml
- .github/workflows/main.yml
- src/pages/api/add_external_account.ts
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/cardholders.ts
- src/pages/api/cards/[cardId]/card-keys.ts
- src/pages/api/cards/[cardId]/switch-card-status.ts
- src/pages/api/cards/index.ts
- src/pages/api/create_paymentlink.ts
- src/pages/api/create_payout.ts
- src/pages/api/create_receivedcredit.ts
- src/pages/api/onboard.ts
- src/pages/api/register.ts
- src/pages/api/send_money.ts
- src/pages/test-data.tsx
- src/utils/onboarding-helpers.ts
- src/utils/stripe-loader.ts
- src/utils/stripe_helpers.ts
* Adds CI check using GitHub actions
> Add CI using GitHub actions

- src/components/issuing/authorizations-table.tsx
- src/components/severity-pill.tsx
- src/sections/overview/overview-latest-transactions.tsx
- src/sections/overview/transaction-flow-details.tsx
- src/theme/colors.ts
- src/theme/create-components.ts
- src/theme/create-palette.ts
- src/theme/create-shadows.ts
- src/theme/create-typography.ts
- src/theme/index.ts
- src/types/mui.d.ts
* Fixes theme generation TypeScript errors by adding proper types
> Fix theme generation TypeScript errors

- src/pages/api/add_external_account.ts
- src/pages/api/cards/[cardId]/card-keys.ts
- src/pages/test-data.tsx
* Removes the last bits of remaining TypeScript error suppression
> Remove last remaining TypeScript error suppression

- src/pages/auth/register.tsx
- src/pages/financial_account.tsx
* Fixes a bug where if the FA isn't setup, it broke the FA page
> Fix financial account pending setup breaking page

- src/pages/financial_account.tsx
- src/pages/index.tsx
- src/sections/test-data/test-data-create-received-credit.tsx
* Shows a message if the FA isn't ready yet
> Wait for FA to be ready before trying to use it

- src/pages/api/add_external_account.ts
- src/pages/api/cardholders.ts
- src/pages/api/cards/[cardId]/card-keys.ts
- src/pages/api/cards/[cardId]/switch-card-status.ts
- src/pages/api/cards/index.ts
- src/pages/api/create_paymentlink.ts
- src/pages/api/create_payout.ts
- src/pages/api/create_receivedcredit.ts
- src/pages/api/onboard.ts
- src/pages/api/register.ts
- src/pages/api/send_money.ts
- src/pages/auth/login.tsx
- src/pages/auth/register.tsx
- src/pages/onboard.tsx
- src/sections/[cardId]/card-illustration.tsx
- src/sections/[cardId]/card-status-switcher.tsx
- src/sections/cardholders/cardholder-create-widget.tsx
- src/sections/cardholders/cardholder-update-widget.tsx
- src/sections/financial-account/send-money-wizard-dialog.tsx
- src/sections/test-data/test-data-create-payment-link.tsx
- src/sections/test-data/test-data-create-payout.tsx
- src/sections/test-data/test-data-create-received-credit.tsx
- src/utils/api-helpers.ts
- Handles async callbacks when handling API response result
- Uses verb specific methods for fetching from the API
- Extracts out a system for handler mappings to HTTP verbs
- Make the loading of the card illustration less jarring
> Use a consistent API communication pattern

- .env.local.example
- README.md
- render.yaml
- Reverts trying to simplify the environment variables using re-assignment. It doesn't work properly on Render.com.
> Revert simplifying environment variables

- src/components/floating-test-panel.tsx
- src/components/issuing/authorizations-table.tsx
- src/layouts/dashboard/config.tsx
- src/layouts/dashboard/top-nav.tsx
- src/pages/authorizations.tsx
- src/pages/authorizations/[authorizationId].tsx
- src/pages/cardholders.tsx
- src/pages/cards.tsx
- src/pages/cards/[cardId].tsx
- src/pages/financial_account.tsx
- src/sections/cardholders/cardholder-create-widget.tsx
- src/sections/financial-account/send-money-wizard-dialog.tsx
- src/sections/overview/overview-fa-funds-flow-chart.tsx
- src/sections/overview/overview-latest-transactions.tsx
- src/sections/test-data/test-data-create-payment-link.tsx
- src/sections/test-data/test-data-create-payout.tsx
- src/sections/test-data/test-data-create-received-credit.tsx
This tackles the issues mentioned in the PR title associated with these 3 rows from the tracking spreadsheet:
- https://docs.google.com/spreadsheets/d/1-IkJ_CiUINMXAC_lEHujUQeWCONS8cufBCgoi86V0Cg/edit#gid=0&range=B10
- https://docs.google.com/spreadsheets/d/1-IkJ_CiUINMXAC_lEHujUQeWCONS8cufBCgoi86V0Cg/edit#gid=0&range=B21
- https://docs.google.com/spreadsheets/d/1-IkJ_CiUINMXAC_lEHujUQeWCONS8cufBCgoi86V0Cg/edit#gid=0&range=B22
Here are some screenshots:
> Change buttons/titles to sentence case, remove non-functional buttons, rename "Authorizations" to "Card authorizations"

- src/layouts/auth/layout.tsx
- src/layouts/dashboard/layout.tsx
- src/pages/auth/register.tsx
- src/pages/onboard.tsx
- src/sections/test-data/test-data-create-received-credit.tsx
- Updates various pages to have clearer copy
- Adds privacy policy and terms links
> Update copy changes and add privacy policy link

- src/pages/financial_account.tsx
- src/sections/test-data/test-data-create-received-credit.tsx
- Tweaks the copy for when the financial account is still being setup
> Make copy changes for financial account setup

- src/pages/auth/login.tsx
- Fixes the handling of the invalid login credentials error message
> Fix handling of invalid login credentials

- src/layouts/dashboard/config.tsx
- src/pages/api/delete-account.ts
- src/pages/settings.tsx
- src/sections/settings/settings-delete-account.tsx
- Allows deleting the account completely
> Allow deleting account completely

- src/layouts/auth/layout.tsx
- Updates copy to reduce number of lines in mobile
> Update copy to reduce number of lines in mobile

- src/pages/onboard.tsx
- Adds copy for account inactivity deletion after 6 months
> Add copy for account inactivity deletion

- src/layouts/auth/layout.tsx
- Updates landing page copy to reduce line numbers on mobile
> Update landing page copy to reduce line numbers on mobile

- src/pages/api/create_authorization.ts
- src/pages/cards/[cardId].tsx
- src/sections/test-data/test-data-create-authorization.tsx
Uses the new authorization test helpers to create and capture a test authorization.
> add flow for creating test purchase

- src/pages/api/create_authorization.ts
- src/pages/cards/[cardId].tsx
- src/sections/test-data/test-data-create-authorization.tsx
- Removes hiding of the generate test purchases drawer for the public demo
> Remove hiding generating test purchases for demo

- src/pages/_app.tsx
- Fixes URL to point to the assets directory for the open graph image
> Update URL to point to assets directory

- src/layouts/dashboard/side-nav.tsx
- Tweaks the alignment of the text so that it looks more centered
> Tweak text alignment

- README.md
- src/layouts/auth/layout.tsx
- Updates the links to our latest docs URLs
- Makes the README a standalone guide for developers who want to get started with local development
> Update URLs to docs and make README standalone for developers

- render.yaml
- Updates the render.yaml config to generate the prisma client when deploying. This is important after deploying a new database migration.
> Always generate the prisma client when deploying

- src/pages/auth/login.tsx
Okay this is the actual solution for the problem I thought I'd fixed in #257.
> Fix infinite loop when callback url was empty or "/"

- src/components/currency-icon.tsx
- src/pages/api/onboard.ts
- src/pages/api/register.ts
- src/pages/index.tsx
- src/sections/overview/balance-transaction-flow-details.tsx
- src/sections/overview/overview-acquring-balance.tsx
- src/sections/overview/overview-balance-funds-flow-chart.tsx
- src/sections/overview/overview-issuing-balance.tsx
- src/sections/overview/overview-latest-balance-transactions.tsx
- src/types/chart-data.ts
- src/utils/stripe_helpers.ts
Adapts the index/homepage of the sample app to support Issuing balance data when the user is not using Treasury financial accounts. Also adds multi-currency support to this page!
> Expense management sample 4: Index page for users with Issuing balances

- src/pages/api/cardholders.ts
- src/pages/api/onboard.ts
- src/pages/api/register.ts
- src/pages/auth/register.tsx
- src/pages/onboard.tsx
- src/sections/cardholders/cardholder-create-widget.tsx
- src/utils/validation_schemas.ts
Pulls out some disparate (and sometimes duplicated) validation schemas into one central file. Just a refactor, doesn't actually change any behaviour
> Expense management sample 6: Centralize some validations

- src/components/issuing/authorizations-table.tsx
- src/pages/api/cards/index.ts
- src/pages/api/create_authorization.ts
- src/pages/authorizations/[authorizationId].tsx
- src/pages/cards/[cardId].tsx
- src/sections/[cardId]/latest-card-authorizations.tsx
- src/sections/test-data/test-data-create-authorization.tsx
- src/utils/validation_schemas.ts
Adds a localized card management screens and authorization request simulation for non-US regions and non-embedded finance use cases.
> Expense management sample 7: Localize card and auth management 

- src/layouts/dashboard/account-popover.tsx
- src/layouts/dashboard/config.tsx
- src/pages/index.tsx
- src/sections/overview/overview-payments-balance.tsx
Just a grab bag of little tweaks, including:
* Some comments explaining conditional nav choices
* Shows the user's country in the account popover
* Renames "acquiring" to be "payments" (balance)
> Expense management sample 9: Various tweaks

- src/layouts/dashboard/config.tsx
- src/pages/cards/[cardId].tsx
- src/pages/onboard.tsx
Fixes an issue on the navigation (was not hiding links appropriately, as a result of a bad merge resolution by me earlier!) and better localizes the Card view screen.
> A few localization tweaks and bug fixes

- prisma/migrations/20240124202125_rename_use_case_column/migration.sql
- prisma/schema.prisma
- src/layouts/dashboard/config.tsx
- src/layouts/dashboard/side-nav.tsx
- src/pages/api/add_external_account.ts
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/cards/index.ts
- src/pages/api/create_authorization.ts
- src/pages/api/onboard.ts
- src/pages/api/register.ts
- src/pages/auth/register.tsx
- src/pages/index.tsx
- src/pages/onboard.tsx
- src/pages/test-data.tsx
- src/types/financial_product.ts
- src/types/next-auth.d.ts
- src/utils/authentication.ts
- src/utils/validation_schemas.ts
Because it matches what we say in the UI better. Also inlines some conditionals, to make it easier for codegen later.
> Rename `UseCase` to `FinancialProduct`

- embedded-finance/src/types/next-auth.d.ts
- expense-management/src/types/next-auth.d.ts
- Updates some codegen output that was missed
> Update codegen output

- _base/src/layouts/dashboard/layout.tsx
- _base/src/layouts/dashboard/side-nav.tsx
- embedded-finance/src/layouts/dashboard/layout.tsx
- embedded-finance/src/layouts/dashboard/side-nav.tsx
- expense-management/src/layouts/dashboard/layout.tsx
- expense-management/src/layouts/dashboard/side-nav.tsx
- Updates copy to reflect different financial products at play
> Update copy to reflect different capabilities

- _base/src/layouts/dashboard/layout.tsx
- embedded-finance/src/layouts/dashboard/layout.tsx
- expense-management/src/layouts/dashboard/layout.tsx
- Updates copy to reflect different use cases. Fixes missed spots.
> Update copy to reflect different capabilities (part 2)

- _base/package-lock.json
- _base/package.json
- _base/src/pages/api/register.ts
- embedded-finance/package-lock.json
- embedded-finance/package.json
- embedded-finance/src/pages/api/register.ts
- expense-management/package-lock.json
- expense-management/package.json
- expense-management/src/pages/api/register.ts
- package-lock.json
- Changed how accounts are created to follow the new UA model (thanks to @braiden-stripe [here](https://github.com/stripe-samples/issuing-treasury/pull/340))
- Bumped the Stripe package across all the sub-apps and `_base` app
> Moving sample app to UA

- _base/src/pages/api/cardholders.ts
- embedded-finance/src/pages/api/cardholders.ts
- expense-management/src/pages/api/cardholders.ts
- Fixes the way the timestamp for cardholder ToS acceptance was being generated
> Fix cardholder ToS acceptance timestamp

- _base/src/sections/cardholders/cardholder-create-widget.tsx
- _base/src/utils/demo-helpers.ts
- embedded-finance/src/sections/cardholders/cardholder-create-widget.tsx
- embedded-finance/src/utils/demo-helpers.ts
- expense-management/src/sections/cardholders/cardholder-create-widget.tsx
- expense-management/src/utils/demo-helpers.ts
- Uses a localized faker for phone number generation
> Use new faker generation for localized phone numbers

- _base/src/pages/api/create_receivedcredit.ts
- _base/src/pages/api/onboard.ts
- _base/src/pages/api/register.ts
- _base/src/pages/api/send_money.ts
- _base/src/utils/account-management-helpers.ts
- embedded-finance/src/pages/api/create_receivedcredit.ts
- embedded-finance/src/pages/api/onboard.ts
- embedded-finance/src/pages/api/register.ts
- embedded-finance/src/pages/api/send_money.ts
- embedded-finance/src/utils/account-management-helpers.ts
- expense-management/src/pages/api/onboard.ts
- expense-management/src/utils/account-management-helpers.ts
- Supports country currency selection using a helper lookup rather than hardcoding. Mostly impacts the embedded finance financial product.
> Support country currency selection using a helper lookup rather than hardcoding

- _base/src/pages/api/create_account_session.ts
- _base/src/pages/financial-account.tsx
This fixes lint issues stemming from https://github.com/stripe-samples/issuing-treasury/pull/368. See https://dashboard.render.com/web/srv-cjahredm2m9c73drb45g/deploys/dep-ctcqi8lumphs73b79pig?r=2024-12-11%4014%3A59%3A51%7E2024-12-11%4015%3A03%3A06 for logs.
> Fix lint issues

- _base/src/pages/api/cardholders.ts
- _base/src/utils/demo-helpers.ts
- embedded-finance/src/pages/api/cardholders.ts
- embedded-finance/src/utils/demo-helpers.ts
- expense-management/src/pages/api/cardholders.ts
- expense-management/src/utils/demo-helpers.ts
- package-lock.json
- Fixes cardholder generation that was creating a superfluous "ext. " at the end of the phone number after parsing it
> Fix cardholder phone number generation

- _base/src/pages/api/onboard.ts
- _base/src/utils/demo-helpers.ts
- embedded-finance/src/pages/api/onboard.ts
- embedded-finance/src/utils/demo-helpers.ts
- expense-management/src/pages/api/onboard.ts
- expense-management/src/utils/demo-helpers.ts
Fixes fiscal year issue preventing onboarding
> Fix fiscal year issue preventing onboarding

- consumer-issuing/src/components/transaction-details-panel.tsx
- consumer-issuing/src/sections/test-data/test-data-make-payment.tsx
(See individual commits for details.)
> Add some polish to repayments
