.env.example, README.md, package-lock.json, package.json, render.yaml, src/pages/api/register.ts, src/pages/onboard.tsx, src/sections/test-data/test-data-create-received-credit.tsx, src/utils/onboarding-helpers.ts
* Adds a button to the README file to deploy to Render.com
* Adds a `render.yaml` file to configure the infrastructure to quickly deploy a publicly accessible free demo
=> Add deploy to render support

.eslintrc.json, src/pages/api/onboard.ts, src/pages/onboard.tsx
* Does a full reload after skipping onboarding by using `window.location.replace`
=> Tweak redirect when skipping onboarding (Part 2)

src/components/authorizations-table.tsx, src/components/floating-test-panel.tsx, src/components/issuing/authorizations-table.tsx, src/layouts/dashboard/account-popover.tsx, src/layouts/dashboard/config.tsx, src/pages/authorizations.tsx, src/pages/authorizations/[authorizationId].tsx, src/pages/cards/[cardId].tsx, src/sections/[cardId]/latest-card-authorizations.tsx, src/utils/format.ts, src/utils/stripe_helpers.ts
* Adds an authorization page to show all authorizations
* Updates the authorization table on the card details page
* Links from both of the above to an authorization details page
* Card details page has a new "Generate Test Data" button that opens a MUI drawer to help with creating test authorizations
=> Add authorization pages and test data generation UI

src/layouts/dashboard/account-popover.tsx, src/pages/cards/[cardId].tsx, src/pages/onboard.tsx, src/sections/test-data/test-data-create-payment-link.tsx, src/sections/test-data/test-data-create-payout.tsx, src/sections/test-data/test-data-create-received-credit.tsx
* Hides debug related UIs behind a query parameter `?debug=true` or if the environment variable `NEXT_PUBLIC_DEMO_MODE` is set to true
* Changes the checkbox for skipping onboarding to be on by default
=> Hide debug UI behind a query parameter or if in demo mode

src/pages/onboard.tsx
* Adds a dialog explaining how to enter test data in connect onboarding that is shown when the user unchecks the "Skip onboarding using prefilled info"
=> Add a dialog explaining how to enter test data in connect onboarding

src/layouts/auth/layout.tsx, src/layouts/dashboard/config.tsx, src/layouts/dashboard/side-nav.tsx, src/pages/_app.tsx, src/pages/api/cardholders.ts, src/pages/api/create_receivedcredit.ts, src/pages/financial_account.tsx, src/pages/index.tsx, src/pages/test-data.tsx, src/sections/cardholders/cardholder-create-widget.tsx, src/sections/test-data/test-data-create-received-credit.tsx
* Moves the simulate received credit button to the FA and overview pages
* Removes the settings page until we have something we need to put there
* Fixes the title for all pages
* Updates cookie notice wording
* Fixes the cardholder TOS acceptance not being enforced
* Tweaks side-nav demo notice at the bottom left
=> Move simulate received credit button

src/components/floating-test-panel.tsx, src/layouts/dashboard/account-popover.tsx, src/layouts/dashboard/layout.tsx, src/layouts/dashboard/side-nav.tsx, src/pages/cards/[cardId].tsx, src/pages/onboard.tsx, src/sections/cardholders/cardholder-create-widget.tsx, src/sections/cardholders/cardholder-update-widget.tsx, src/sections/financial-account/send-money-wizard-dialog.tsx, src/sections/test-data/test-data-create-received-credit.tsx
* Adds a close button to the floating test panel so that it can be closed on mobile
* Fixes alignment of the arrow icon used to denote a link that'll open in a new tab
* Adds a disclaimer about no actual financial activity to the bottom left
* Updates disclosures and ToS to be bank agnostic
=> Add close button to floating test panel and update disclosures

src/sections/cardholders/cardholder-create-widget.tsx
* Tweaks the bank terms link for Cardholder ToS to be an example instead of real
Note: Real production implementations of the sample app needs to fill these URLs with proper ones pointing to the appropriate bank terms
=> Tweak bank terms link to be an example instead of real

render.yaml
* Shows the publishable key at the top when prompted to match what people see on the Stripe dashboard
=> Tweak Render environment variable ordering

README.md
Adds a link to get your Stripe account automatically into testmode Issuing and Treasury
=> Add link to Issuing and Treasury sign up

next.config.mjs, src/sections/overview/transaction-flow-details.tsx
* Adds `Content-Security-Policy` security headers
* Fixes alignment issue with the transaction flow details icon
We are setting the content security policy as strictly as possible. There are a few notable exceptions being made:
- We are allowing 'unsafe-eval' in the script-src directive in development only because we are using Next.js' built-in support for React Fast Refresh. This is a temporary exception until Next.js supports a better solution for Fast Refresh.
- We are allowing 'unsafe-inline' in the style-src directive. This is a temporary exception until Next.js supports a better solution. [The risk of keeping this is minimal](https://scotthelme.co.uk/can-you-get-pwned-with-css/) and we'll keep it until there's broader support in the community.
- We are allowing fonts.gstatic.com and …
=> Add `Content-Security-Policy` security headers

src/utils/stripe-loader.ts
- Sets the app info on the Stripe backend client in order to run analytics
=> Set the starter application name for analytics

src/pages/api/send_money.ts, src/pages/authorizations/[authorizationId].tsx
This adds the decline reason for declined auths on the auth details page (see [tracking spreadsheet](https://docs.google.com/spreadsheets/d/1-IkJ_CiUINMXAC_lEHujUQeWCONS8cufBCgoi86V0Cg/edit#gid=0&range=B19)). For non-declined auths, we won't show a decline reason.
Declined auth details page:
Approved auth details page:
This also updates the `account_holder_type` to "company" for outbound payments, per https://docs.google.com/document/d/1Elfsh36muNpqbq0Qjzztc4IfnHiQaYv59wt9rLEGtTg/edit?disco=AAAA4rgP5To
=> Display decline reason for declined auths on auth details page and update `account_holder_type` to "company"

src/pages/api/onboard.ts
- Fixes onboarding in demo mode that was broken due to additional KYC/KYB requirements
- Phone number is being validated using livemode logic currently so temporarily providing a fake non "0000000000" number until the bug is fixed at Stripe Connect Onboarding
=> Fix onboarding in demo mode

src/pages/api/add_external_account.ts, src/pages/api/create_paymentlink.ts, src/pages/api/create_payout.ts, src/pages/test-data.tsx, src/sections/test-data/test-data-create-payout-to-bank.tsx
Localizes the experience for paying out outstanding balances to external accounts, and adapts it for expense management use cases (i.e. setups that do not pay out to a Treasury financial account)
=> Expense management sample 8: Localize payouts to external accounts

src/pages/api/register.ts
- `card_payments` capability is not required to be requested along with `card_issuing` or `treasury` so remove it from being requested
=> Remove requesting card payments capability

_base/src/pages/api/register.ts, _base/src/sections/overview/overview-payments-balance.tsx, embedded-finance/src/pages/api/register.ts, expense-management/src/pages/api/register.ts, expense-management/src/sections/overview/overview-payments-balance.tsx
- Related to https://github.com/stripe-samples/issuing-treasury/issues/298. Reverts removing requesting of `card_payments` for now. In the future, we'll move requesting from the register flow to come later when someone goes and clicks on "Enable Payments" or something in the current "Test Data" section.
- After this deploys, I'll manually request the `card_payments` capability for all the existing users that don't have it.
=> Revert removing requesting card_payments

_base/README.md, render.yaml
- Fixes [#342](https://github.com/stripe-samples/issuing-treasury/issues/342)
- Simplifies the Render deployment so that it only uses the default US region keys without a region suffix. The code to do it with multi-region on Render is still there but commented out.
- Fixes the `POSTGRES_URL`/`DATABASE_URL` environment variable being broken in the Render deployment
=> Fix render yaml not being in the root

_base/README.md, _base/src/layouts/dashboard/layout.tsx, _base/src/layouts/dashboard/side-nav.tsx, _base/src/pages/_app.tsx, embedded-finance/src/layouts/dashboard/layout.tsx, embedded-finance/src/layouts/dashboard/side-nav.tsx, embedded-finance/src/pages/_app.tsx, expense-management/src/layouts/dashboard/layout.tsx, expense-management/src/layouts/dashboard/side-nav.tsx, expense-management/src/pages/_app.tsx
- Renames references to the sample app to "Stripe BaaS platform demo" for consistency
=> Rename references to the sample app to BaaS platform demo

_base/src/utils/demo-helpers.ts, embedded-finance/src/utils/demo-helpers.ts, expense-management/src/utils/demo-helpers.ts
- Expands the fake address generation for demo purposes to use a localized faker instance whenever possible
- There are some countries that don't have a localized faker instance. Next step would be to make sure we hard-code some demo values if they are problematic with frontend/backend validation for these countries.
=> Expand fake address generation to use localized faker

_base/src/pages/api/onboard.ts, embedded-finance/src/pages/api/onboard.ts, expense-management/src/pages/api/onboard.ts
- Reverts back to using actual testmode valid phone number. We had to temporarily use some other number to get through because there was a defect on Stripe's test values
=> Revert back to using actual testmode valid phone number
